{
 "title": "RabbitMQ Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Site", "query": "DC1,DC2" }
  ]
 },
 "panels": [
  {
   "title": "Cluster nodes running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(mycustomprefix.rabbitmq.$Site.nodes.*.node_running)"
    }
   ]
  },
  {
   "title": "Cluster number of queues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(mycustomprefix.rabbitmq.$Site.queues_total_count)"
    }
   ]
  },
  {
   "title": "Cluster number of exchanges",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(mycustomprefix.rabbitmq.$Site.exchanges_total_count)"
    }
   ]
  },
  {
   "title": "Cluster Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(mycustomprefix.rabbitmq.$Site.connections_total_count, 2, 3)"
    }
   ]
  },
  {
   "title": "Cluster channels",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(mycustomprefix.rabbitmq.$Site.channels_total_count, 2, 3)"
    }
   ]
  },
  {
   "title": "Cluster consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(mycustomprefix.rabbitmq.$Site.consumers_total_count, 2, 3)"
    }
   ]
  },
  {
   "title": "Cluster queues consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(mycustomprefix.rabbitmq.$Site.queues.*.consumers, 4)"
    }
   ]
  },
  {
   "title": "Cluster Queues messages ready",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(mycustomprefix.rabbitmq.$Site.queues.*.messages_ready, 3, 4, 5)"
    }
   ]
  },
  {
   "title": "Cluster Queues messages unacknowledged",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(mycustomprefix.rabbitmq.$Site.queues.*.messages_unacknowledged, 4, 5)"
    }
   ]
  },
  {
   "title": "Cluster Nodes memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "mycustomprefix.rabbitmq.$Site.nodes.*.node_mem_used"
    }
   ]
  },
  {
   "title": "Cluster Node file descriptor used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "mycustomprefix.rabbitmq.$Site.nodes.*.node_file_descriptor_used"
    }
   ]
  }
 ]
}